spring:
  # DB Connection
  datasource:
    url: jdbc:postgresql://localhost:5432/forum_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  # JPA settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


# permet de changer le format par défaut des dates
#  mvc:
#    format:
#      date: dd/MM/yyyy
#      date-time: dd/MM/yyyy HH:mm:ss
#      time: HH:mm:ss
